events {
    worker_connections 1024;
}

http {
    # DNS của Docker để Nginx cập nhật IP của các container mới
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;
        server_name localhost;

        # Sử dụng biến để ép Nginx phải phân giải DNS lại liên tục
        set $backend_upstream "http://nextjs:3000";

        location / {
            proxy_pass $backend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}